# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5e6b3f392a34d597da0f073b1d81ccfa0d282eba2defff3d56e58b7f74060aafc3abc33057de0733b554e080f7d61b33d3a6a183996e786326ec27b6f132cdf

test:
  secret_key_base: 4743bac728d88ec5e65dab3600d46e66488906876d17c3ac366e49f727d84c8a65434bd1b6675db069b8250826dd3fc8573c6c136fcdf0904a32aec89364bd72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
